services:
  database:
    image: postgres:16-alpine
    restart: always
    env_file:
      - '.env'
    ports:
      - '5432:5432'
    volumes:
      - '/var/tmp'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
