services:
  database:
    image: postgres:16-alpine3.20
    restart: always
    env_file:
      - '.env'
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - database-volume:/etc/data

volumes:
  database-volume:
