services:
  backend:
    container_name: backend
    env_file:
      - '.env'
    image: leftovers-backend:latest
    platform: linux/arm64
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    networks:
      - leftovers-network
    depends_on:
      database:
        condition: service_healthy
    restart: always

  database:
    container_name: database
    image: postgres:16-alpine3.20
    restart: always
    env_file:
      - '.env'
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - database-volume:/var/lib/postgresql/data
    networks:
      - leftovers-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  database-volume:

networks:
  leftovers-network:
    driver: bridge
